name: streamit_flutter
description: A new Flutter application.
version: 9.4.0+54

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Required
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  nb_utils: ^6.1.0
  cached_network_image: ^3.4.1
  flutter_vector_icons: ^2.0.0
  google_nav_bar: ^5.0.7

  # Html
  html: ^0.15.4
  http: ^1.2.2
  flutter_html: ^3.0.0-beta.2

  # Voice Search
  speech_to_text: ^7.0.0

  # State Management
  mobx: ^2.5.0
  flutter_mobx: ^2.3.0

  # Font
  google_fonts: ^6.2.1

  # Launch url
  url_launcher: ^6.3.1

  # Rating
  flutter_rating_bar: ^4.0.1

  # Ads
  google_mobile_ads: ^5.2.0

  # Image selection
  image_picker: ^1.1.2

  # Video player
  youtube_player_flutter: ^9.1.1
  pod_player: ^0.2.2
  cast: ^2.1.0

  # Web-views
  webview_flutter: ^4.9.0
  flutter_custom_tabs: ^2.1.0

  # Animation
  lottie: ^3.3.0

  # Firebase remote config
  firebase_core: ^3.9.0
  firebase_remote_config: ^5.2.0
  firebase_crashlytics: ^4.2.0

  #Firebase Notification
  flutter_local_notifications: ^18.0.1
  firebase_messaging: ^15.1.6

  # Prevent Screenshot and Screen record
  screen_protector: ^1.4.2+1

  # shimmer effect
  shimmer: ^3.0.0

  # Share link
  share_plus: ^10.1.3



  # Download file and store
  flutter_downloader: ^1.11.8
  device_info_plus: ^11.2.0
  permission_handler: ^11.3.1
  path_provider: ^2.1.5

  #others
  percent_indicator: ^4.2.4
  stream_transform: ^2.1.1
  fl_pip: ^3.2.0



  flutter_localizations:
    sdk: flutter
  encrypt: ^5.0.3


  # in App Purchase
  purchases_flutter: ^8.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.7.0
  build_runner: ^2.4.14
  #flutter packages pub run build_runner build --delete-conflicting-outputs

dependency_overrides:
  flutter_widget_from_html_core: ^0.15.2

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/lottie/
    - assets/gif/
    - assets/images/
    - assets/images/flag/
    - assets/
